### ISSUE TITLE
I Just Don't Understand

### ISSUE THREAD

**Issue by HimaOtaku** [lyger/Aegisub_automation_scripts#7]
I'm really confused on how to make this script work. I know I need to install DependencyControl and stuff, but I really don't understand how to make any of it work. Assume I am a complete noob because I am. Please teach me, this is one of the most useful scripts.

Here is the log:

20:20:54: A script in the Automation autoload directory failed to load.
Please review the errors, fix them and use the Rescan Autoload Dir button in Automation Manager to load the scripts again.
20:20:54: Failed to load Automation script 'C:\Program Files\Aegisub\automation\autoload\gradient.moon':
Error initialising Lua script "gradient.moon":

[string "C:/Program Files\Aegisub\automation\autoload\..."]:45: module 'l0.DependencyControl' not found:
	no field package.preload['l0.DependencyControl']
	no file '.\l0\DependencyControl.dll'
	no file 'C:\Program Files\Aegisub\l0\DependencyControl.dll'
	no file 'C:\Program Files\Aegisub\loadall.dll'
	no file '.\l0.dll'
	no file 'C:\Program Files\Aegisub\l0.dll'
	no file 'C:\Program Files\Aegisub\loadall.dll'

**Comment by FichteFoll** [comment]
Download a build with depctrl preinstalled from http://files.line0.eu/builds/Aegisub/.

**Comment by HimaOtaku** [comment]
![image](https://cloud.githubusercontent.com/assets/13340984/8689303/ca409954-2a73-11e5-9017-51464377e0d8.png)

**Comment by lyger** [comment]
This issue was moved to TypesettingTools/lyger-Aegisub-Scripts#1

**Comment by lyger** [comment]
This issue was moved to TypesettingTools/lyger-Aegisub-Scripts#2

**Comment by firecrauter** [comment]
> This issue was moved to [TypesettingTools#2](https://github.com/TypesettingTools/lyger-Aegisub-Scripts/issues/2)

pls, reupload the "build with depctrl preinstalled",  I don't know how to install DependencyControl/etc

**Comment by firecrauter** [comment]
> Download a build with depctrl preinstalled from http://files.line0.eu/builds/Aegisub/.

pls, reupload x2

**Comment by FichteFoll** [comment]
https://thevacuumof.space/builds/
