### ISSUE TITLE
Gradient Everything generates blank lines

### ISSUE THREAD

**Issue by Susexe** [lyger/Aegisub_automation_scripts#8]
I installed a build with DepCtrl preinstalled, but I can't get Gradient Everything to work. It generates blank lines for some reason. Right after I installed it, it worked one time, but now it doesn't even though I tried numerous times. Here's a sample .ass file: http://pastebin.com/MNMNMB6r. I tried both with and without drawing rectangular clip. By the way, when I don't check "\c" field in script options, it works (lines aren't blank), but that's obviously pointless. Thank you in advance.

**Comment by lyger** [comment]
This issue was moved to TypesettingTools/lyger-Aegisub-Scripts#5
